### ISSUE TITLE
Read Grippeimpfstoffe.json created by cpp2sqlite

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#104]
Grippeimpfstoffe.csv muss von cpp2sqlite runtergeladen und nach Grippeimpfstoffe.json konvertiert werden. siehe https://github.com/zdavatz/cpp2sqlite/issues/135

Produkte, welche in der Datei "Grippeimpfstoff.json" gefunden werden, werden wie folgt behandelt: - "shipping" wird `red` mit dem Text: "stock_gui_de": `derzeit nicht auf Lager`,  "stock_gui_fr": `pas actuellement en stock`

**Comment by b123400** [comment]
Guten Tag, was sollen "stock" "stock_zurrose" "stock_voigt" sein, wenn es in der Datei "Grippeimpfstoff.csv" gefunden?

**Comment by zdavatz** [comment]
`stock`, `stock_zurrose`, `stock_voigt` müssen die normalen Zahlen anzeigen.
