### ISSUE TITLE
DM Flag für Dailymed

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#112]
1. Der Override Flag "=dm" (dailymed) kann im URL mitgeben. 
2. Dann werden immer alle Alternativen zu einem Produkt im JSON angezeigt. 
3. Die Kundenpräferenzen werden auch berücksichtigt. 
4. Der Alt-Flag ist bei dieser Option immer auf "maximum" (deaktiviert).

**Comment by b123400** [comment]
> alle Alternativen zu einem Produkt im JSON angezeigt

Ich denke, haben wir schon alle Alternativen zu einem Produkt im JSON angezeigt?

**Comment by b123400** [comment]
Der Alt-Flag ist zur Zeit Integer, ich denke es ist besser Integer zu bleiben, z.B. alt=99999 anstelle "maximum"

**Comment by zdavatz** [comment]
Ok, das macht Sinn!

**Comment by zdavatz** [comment]
> Ich denke, haben wir schon alle Alternativen zu einem Produkt im JSON angezeigt?

Nein, wenn der Alt-Flag `=0` ist werden keine alle Alternativen angezeigt.

**Comment by zdavatz** [comment]
1. Alt-Flag ist >0: https://so.zurrose.ch/smart/full?pretty=on&authkey=xxxxxxxxxx&glncode=945160&basket=(5292970,2). Alle Alternativen kommen.
2. Alt-Flag ist 0: https://so.zurrose.ch/smart/full?pretty=on&authkey=xxxxxxxxxxglncode=945160&basket=(1927437,2). Keine Alternativen kommen.
