### ISSUE TITLE
Original und schwarz

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#128]
1. Wird nach einem Original gesucht und ist shipping `black` dann immer den `alt` auf Maximum stellen wenn der Flag `&override=dm` mitgegeben wird, d.h. alle Alternativen anzeigen (zur Zeit werden nur exakte Alternativen angezeigt auch wenn der Flag `&override=dm` mitgegeben wird).
2. Beispiel `Dancor`
3. `glncode=7601000228512&basket=(2188410,1)`
4. Hier müsste dann auch `NICORANDIL Rivopharm cpr 10 mg 30 pce` kommen unter den Alternativen.
5. Override mit shipping=red klappt wunderbar: `&override=dm&glncode=7601000228512&basket=(7680392710614,1)`

**Comment by b123400** [comment]
Ich habe es versuchen (cpp2sqlite laufen und neue Databank zu machen), und Dancor ist immer grün.

Zur Zeit, wenn der Artikel hat "shipping=black", die Alternativen müssen ein gleiche "Size" hat, z.B. 
- "DANCOR Tabl 10 mg 60 Stk" ist 60
- "NICORANDIL Rivopharm Tabl 10 mg 30" ist 30.

Deshalb "NICORANDIL Rivopharm Tabl 10 mg 30" ist nicht ein Alternative. Mit "alle Alternativen", meinen Sie dass wir sollen Size nicht überlegen?

**Comment by zdavatz** [comment]
Ja, when Shipping "black" ist, scheint &override=dm nicht zu klappen. Die anderen Pacckungsgrössen kommen dann nicht. Wenn &override=dm gesetzt ist, ist normalerweise eine Packungsgrössenabweichung bis 90% erlaubt.

**Comment by zdavatz** [comment]
oder noch einfacher shipping=black gleich behandeln wie shipping=red.
