### ISSUE TITLE
enable JSON file loading

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#3]
Die folgenden Files müssen auch als JSON geladen werden können:

```
rose_autogenerika.ser.clear
rose_ids.ser.clear
rose_conditions.ser.clear
rose_nota.ser.clear
rose_direct_subst.ser.json ?
```

**Comment by b123400** [comment]
Kann Ich mehr Info in der Readme Datei haben? Ich weiss nicht, wie man das Programm starten. Ich habe `./bin/activator run` versuchen, aber es gibt das Error:

```
ERROR: Could not read file smart-order/rose/rose_settings.json
```

Und, wie es lädt die `.ser` Dateien? Wann Ich mache `./bin/activator run`, ein Webserver gestartet, Ich offen mit Browser und es gibt nur `Welcome to AmikoRose`.

Auch, ist `rose_auth_keys.txt` ein Geheimnis? Es ist öffentlich hochgeladen.
https://github.com/zdavatz/smart-order/blob/master/rose/rose_auth_keys.txt
