### ISSUE TITLE
Vergleich geht nur in eine Richtung

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#49]
Der Vergleich mit: `4482993` zeigt `7595404` als Alternative. Jedoch zeigt `7595404` nicht `4482993` als Alternative.

**Comment by zdavatz** [comment]
Das Produkt `7595404` ist nicht im Artikelstamm.csv vorhanden.

**Comment by b123400** [comment]
`4482993` zeigt `7595404` als Alternative, weil:
- Sie haben beide der gliche ATC "G04CA52"
- Sie haben die gliche Dosierung 
- `7595404` ist nicht Original

----

7595404 ist nicht im `artikel_stamm_zurrose.csv` vorhanden, aber es ist im `artikel_vollstamm_zurrose.csv`.

Cpp2Sqlite machen beide `rose_db_new_atc_only.db` und `rose_db_new_full.db` von `artikel_vollstamm_zurrose.csv`.

**Comment by zdavatz** [comment]
Ok, Use-Case 13 wurde ergänzt. Bitte auch im Code ergänzen.
