### ISSUE TITLE
Vergleich bei Produkten mit zwei Wirkstoffen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#57]
![21F1F14E-DC08-47E3-AE80-1BE5E9FB7C95](https://user-images.githubusercontent.com/4953/74233115-6338e800-4cca-11ea-889a-7d3a04ac4ff4.png)

An zweiter Stelle müsste eigentlich das Produkt mit der gleichen Dosierung kommen, nämlich `COVERSUM N Combi Filmtabl 10/2.5 mg Ds 30 Stk`.

Die Dosierung in diesem Fall ist `10/2.5mg` und nicht `2.5/0.625mg`

Dieser Vergleich scheint noch nicht zu klappen. Zuerst kommt immer die Dosierung und dann erst die Packungsgrösse.

**Comment by b123400** [comment]
Ich denke es ist ein Problem mit Cpp2sqlite. In die Databank, PERINDOPRIL hat keine Unit (Dosierung).


![rose_db_new_full db 2020-02-12 18-20-27](https://user-images.githubusercontent.com/127193/74335659-0596bf80-4de0-11ea-9f34-b88cc05337d4.png)

**Comment by zdavatz** [comment]
Kannst Du die Dosierung aus dem Namen rausparsen?

**Comment by zdavatz** [comment]
wir müssen die Option `--pharma` erweitern mit den Beispielen 40 und 41, siehe https://github.com/zdavatz/cpp2sqlite/issues/72

**Comment by zdavatz** [comment]
ist das Feld in der DB leer, dann können wir die Info von der `--pharma` Option verwenden, sobald 40 und 41 funktionieren.

**Comment by zdavatz** [comment]
`COVERSUM N Combi Filmtabl 10/2.5 mg Ds 30 Stk` erscheint noch nicht als Alternative, wenn ich nach 7073628 suche, siehe: https://ywesee.slack.com/archives/C29QYEXND/p1581699329014100

**Comment by zdavatz** [comment]
Wir müssen bei SO `ds` gleich behandeln wie `mg`

<img width="727" alt="Bildschirmfoto 2020-02-14 um 19 28 17" src="https://user-images.githubusercontent.com/4953/74557369-4cabbe80-4f60-11ea-9ce4-bd757a1f62dd.png">

`ds` müssen wir auch rausparsen, siehe 40 und 41 bei https://github.com/zdavatz/cpp2sqlite/issues/72

**Comment by zdavatz** [comment]
es kann nur 160/12.5 miteinander verglichen werden. `160/12.5` kann man nicht mit `80/12.5` vergleichen.
![co-valsartan](https://user-images.githubusercontent.com/4953/75452602-e5840600-5972-11ea-8514-c494840ae4c2.png)
