### ISSUE TITLE
Vergleich mit 3 Wirkstoffen braucht noch kleine Verbesserung

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/smart-order#65]
Siehe: https://ywesee.slack.com/archives/C29QYEXND/p1585584656000500

Es wird `25` wird nicht richtig mit `12.5mg` verglichen. Ich denke es braucht hier noch eine kleine Anpassung.

**Comment by b123400** [comment]
Es ist ein Problem mit cpp2sqlite, Ich habe eine PR gesendet: https://github.com/zdavatz/cpp2sqlite/pull/121

**Comment by zdavatz** [comment]
ok, Danke!
